title: "Hector Cid del prado Soto"
portfolio_link: "https://github.com/Hectorcidps/Portfolio_DA"
logo: assets/perfil.png
description: "🚀 ¡Bienvenido a mi portafolio! Aquí muestro mis proyectos más relevantes en análisis de datos, aplicando herramientas como Python, SQL, Power BI y Tableau. Soy una persona entusiasta, extrovertida y con facilidad para trabajar en equipo. Me apasiona aprender de manera autodidacta y estoy listo para enfrentar nuevos retos."  

# 🔹 Información de contacto
contact:
  email: "Hectorcidps@gmail.com"
  linkedin: "https://www.linkedin.com/in/hector-cid-del-prado/"
  whatsapp: "https://wa.me/525531398543"
theme: jekyll-theme-minimal
show_downloads: false
github: 
    is_project_page: false

