title: "Hector Cid del Prado"
logo: assets/Hector Cid.jpeg
description: "Mi portafolio de análisis de datos"
theme: jekyll-theme-minimal
show_downloads: false
github:
  is_project_page: false
url: "https://github.com/Hectorcidps/Portfolio_DA"
